# -*- coding: utf-8 -*-
"""assignment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xIxD_p01HayRYSfpua7vLCynK9d16OCr
"""



"""## Q  If you could invite anyone, living or deceased, to dinner, who would you invite? Make a list that includes at least three people you’d like to invite to dinner . Then use your list to print a message to each person, inviting them to dinner . 

"""

shabana_friend =["munazah","rehana","asma"];
print("dear "+shabana_friend[0]+","+shabana_friend[1]+","+shabana_friend[2]+" you all are invited to dinner")

"""Q## 3.5-- You just heard that one of your guests can’t make the dinner, so you need to send out a new set of invitations . You’ll have to think of someone else to invite . •	Start with your program from Exercise 3-4 . Add a print statement at the end of your program stating the name of the guest who can’t make it . •	Modify your list, replacing the name of the guest who can’t make it with the name of the new person you are inviting . •	Print a second set of invitation messages, one for each person who is still in your list ."""

shabana_friend =["munazah","rehana","asma"]; 
print(shabana_friend[2]+" will not be able to join us on dinner")

shabana_friend[2] = "hira";
print("dear "+shabana_friend[0]+", you all are invited to dinner")
print("dear "+shabana_friend[1]+", you all are invited to dinner")
print("dear "+shabana_friend[2]+", you all are invited to dinner")

"""Q# 3.6  You just found a bigger dinner table, so now more space is available . Think of three more guests to invite to dinner . •	Start with your program from Exercise 3-4 or Exercise 3-5 . Add a print statement to the end of your program informing people that you found a bigger dinner table . •	Use insert() to add one new guest to the beginning of your list . •	Use insert() to add one new guest to the middle of your list . •	Use append() to add one new guest to the end of your list . •	Print a new set of invitation messages, one for each person in your list ."""

print(shabana_friend)

shabana_friend=['munazah','rehana','hira']
print("dear friends, we have enough place. So I am inviting you three pepole.")
shabana_friend.insert(0,'shana')
shabana_friend.insert(2,'insha')
shabana_friend.append('asia')
print("dear "+shabana_friend[0]+", you all are invited to dinner")
print("dear "+shabana_friend[1]+", you all are invited to dinner")
print("dear "+shabana_friend[2]+", you all are invited to dinner")
print("dear "+shabana_friend[3]+", you all are invited to dinner")
print("dear "+shabana_friend[4]+", you all are invited to dinner")
print("dear "+shabana_friend[5]+", you all are invited to dinner")

"""-7. Shrinking Guest List: You just found out that your new dinner table won’t arrive in time for the dinner, and you have space for only two guests . •	Start with your program from Exercise 3-6 . Add a new line that prints a message saying that you can invite only two people for dinner . •	Use pop() to remove guests from your list one at a time until only two names remain in your list . Each time you pop a name from your list, print a message to that person letting them know you’re sorry you can’t invite them to dinner . •	Print a message to each of the two people still on your list, letting them know they’re still invited . •	Use del to remove the last two names from your list, so you have an empty list . Print your list to make sure you actually have an empty list at the end of your program .

"""

shabana_friend= ['shana','munazah','insha','rehana','hira','asia']
print("sorry friend,only two friends cane attend dinner")
friend1_removed=shabana_friend.pop(0)
print("sorry "+friend1_removed+" you cant attend the dinner")
friend2_removed=shabana_friend.pop(0)
print("sorry "+friend2_removed+" you cant attend the dinner")
friend3_removed=shabana_friend.pop(0)
print("sorry "+friend3_removed+" you cant attend the dinner")
friend4_removed=shabana_friend.pop(0)
print("sorry "+friend4_removed+" you cant attend the dinner")
print("dear "+shabana_friend[0]+" you cant attend the dinner")
print("dear "+shabana_friend[1]+" you cant attend the dinner")
del shabana_friend[0]
del shabana_friend[0]
print(shabana_friend)

"""4-1. Pizzas: Think of at least three kinds of your favorite pizza . Store these pizza names in a list, and then use a for loop to print the name of each pizza . •	Modify your for loop to print a sentence using the name of the pizza instead of printing just the name of the pizza . For each pizza you should have one line of output containing a simple statement like I like pepperoni pizza . •	Add a line at the end of your program, outside the for loop, that states how much you like pizza . The output should consist of three or more lines about the kinds of pizza you like and then an additional sentence, such as I really love pizza! """

pizza_shabana= ["Deep Disha","sclian","Greek"]
for i in range(0, len(pizza_shabana)):
  print(pizza_shabana[i])
for k in range(0, len(pizza_shabana)):
  print("I like to eat "+pizza_shabana[k]+" every time")
  print("I like pizza")

"""4-2. Animals: Think of at least three different animals that have a common char- acteristic . Store the names of these animals in a list, and then use a for loop to print out the name of each animal . •	Modify your program to print a statement about each animal, such as A dog would make a great pet. •	Add a line at the end of your program stating what these animals have in common . You could print a sentence such as Any of these animals would make a great pet"""

pet_shabana= ["cat","dog","tiger","cow"]
for x in range(0, len(pet_shabana)):
  print(pet_shabana[x])
for y in range(0,len(pet_shabana)):
  print(pet_shabana[y]+" have four legs")
  print("it is common pet animal")